### PR TITLE
Unhandled error while tsconfig.json isn't valid

### PR DESCRIPTION
**Pull request by gormonn**
I couldn't figure out why your module isn't working with my tsconfig.json. I got into the code, and finding this place, I realized that my json is not valid, because contains commented lines.

At first I was throwing an exception. However, judging by the code, it was meant to be something else. So I left Warn

### CODE REVIEW

**Comment by davestewart** [comment]
Hey, 

Thanks for the PR!

Adding a try/catch to loading JSON seems like a valid request.

I don't understand how you got comments into your JSON in the first place though?

**Comment by gormonn** [comment]
@davestewart 

> Adding a try/catch to loading JSON seems like a valid request.
When experimenting with different options.

> I don't understand how you got comments into your JSON in the first place though?
By hands. :)

> Or how it got parsed by TypeScript...
Correct me if I am wrong.
As far as I understand this is not the task of TypeScript, remaining on the conscience of users. This can be done on the IDE side, or with a linter.

However, VSCode doesn't give any warnings. Even for a seemingly such error (extra comma):
```
"paths": {
      "@/*": [
        "src/*"
      ],
}
```

By the way, for such cases you can use something like this: https://www.npmjs.com/package/json-fixer
The VSC may be using something similar under the hood, however, I can't be sure.

**Comment by gormonn** [comment]
@davestewart 

> I don't understand how you got comments into your JSON in the first place though?

When experimenting with different options.

> Or how it got parsed by TypeScript...

Correct me if I am wrong.
As far as I understand this is not the task of TypeScript, remaining on the conscience of users. This can be done on the IDE side, or with a linter.

However, VSCode doesn't give any warnings. Even for a seemingly such error (extra comma):
```
"paths": {
      "@/*": [
        "src/*"
      ],
}
```

By the way, for such cases you can use something like this: https://www.npmjs.com/package/json-fixer
The VSC may be using something similar under the hood, however, I can't be sure.

**Comment by davestewart** [comment]
I think it's good to fix this.

I'm going to make some additional changes, then will accept this.

Thanks :)

**Pull request merged**
