### PR TITLE
🧪 Tests CI & Coverage Badges

### PR DESCRIPTION
**Pull request by pankajpatel**
Github Actions for
- Test on Push to master
- Coverage Labels on opening PRs 

Check Coverage labels on https://github.com/pankajpatel/alias-hq/pull/1

### CODE REVIEW

**Review by davestewart — APPROVED** [review]
No real idea about this stuff, so will merge. Thanks!

**Comment by davestewart** [comment]
By the way, thanks for this!

It looks pretty complex.

Do you always have to write it yourself, or it a copy/paste job, or does GitHub help you write it?

Would be good to know for future reference.

**Comment by pankajpatel** [comment]
Most of the pieces can be provided by Github though I got to know this by trial and error

Auto publish on npm/git can also be done with Github Actions and there are already built action for it. Both explained here: https://github.com/features#ci-cd

For test coverage labels, I started it on some repos at work and then made a post about it
https://time2hack.com/test-coverage-label-with-github-actions/

**Comment by davestewart** [comment]
Nice one. Yet another thing to look into and get good (good enough) at 🤔  

Anyway, thanks again for all your effort!

**Pull request merged**
